;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Structure & Interpretation of Computer Programs ;;

(assert (= 486 486))
(assert (= (+ 137 349) 486))
(assert (= (- 1000 334) 666))
(assert (= (* 5 99) 495))
(assert (= (/ 10 5) 2))
(assert (= (+ 27/10 10) 127/10))
(assert (= (+ 21 35 12 7) 75))
(assert (= (* 25 4 12) 1200))
(assert (= (+ (* 3 5) (- 10 6)) 19))
(assert (= (+ (* 3 (+ (* 2 4) (+ 3 5))) (+ (- 10 7) 6)) 57))

((fn ()
    (def "size" 2)
    (assert (= size 2))
    (assert (= (* 5 size) 10))

    (def "pi" 314159/100000)
    (def "radius" 10)
    (assert (= (* pi (* radius radius)) 314159/1000))
    (def "circumference" (* 2 pi radius))
    (assert (= circumference 628318/10000))
))
((fn ()
    (defn ("square" "x") (* x x))
    (assert (= (square 21) 441))
    (assert (= (square (+ 2 5)) 49))
    (assert (= (square (square 3)) 81))
    (defn ("sum-of-squares" "x" "y") (+ (square x) (square y)))
    (assert (= (sum-of-squares 3 4) 25))
    (defn ("f" "a") (sum-of-squares (+ a 1) (* a 2)))
    (assert (= (f 5) 136))
))
((fn ()
    (defn ("a-plus-abs-b" "a" "b")
        ((if (< b 0) - +) a b)
    )
    (assert (= (a-plus-abs-b 2 3) 5))
    (assert (= (a-plus-abs-b 2 -3) 5))
))
((fn ()
    (defn ("cube" "x") (* x x x))
    (defn ("inc" "x") (+ 1 x))
    (defn ("sum" "term" "a" "next" "b")
        (if (> a b)
            0
            (+ (term a) (sum term (next a) next b))
        )
    )

    (defn ("sum-cubes" "a" "b") (sum cube a inc b))
    (assert (= (sum-cubes 1 10) 3025))

    (defn ("identity" "x") x)
    (defn ("sum-integers" "a" "b") (sum identity a inc b))
    (assert (= (sum-integers 1 10) 55))
))
((fn ()
    (def "x" 5)
    (assert (=
        (+
            (let (("x" 3))
                (+ x (* x 10))
            )
            x
        )
        38
    ))
))
((fn ()
    (def "x" 2)
    (assert (=
        (let (("x" 3) ("y" (+ x 2)))
            (* x y)
        )
        12
    ))
))
((fn ()
    (defn ("f" "g") (g 2))
    (defn ("square" "x") (* x x))
    (assert (= (f square) 4))
    (assert (= (f (fn ("z") (* z (+ 1 z)))) 6))
))
((fn ()
    (defn ("list-ref" "items" "n")
        (if (= n 0)
            (car items)
            (list-ref (cdr items) (- n 1))
        )
    )
    (def "squares" (list 1 4 9 16 25))
    (assert (= (list-ref squares 3) 16))
))
